### ISSUE TITLE
Provide a sample for Kotlin/JS

### ISSUE THREAD

**Issue by night-crawler** [valiktor/valiktor#34]
## Is your feature request related to a problem? Please describe.
My Gradle build script is configured to produce JavaScript code (`id("org.jetbrains.kotlin.js") version "1.3.70-eap-274"`). I tried adding valiktor-core to the dependencies but I could not import anything from `org.valiktor.*`

## Describe the solution you'd like
Probably, I'm doing it wrong or it does not support JavaScript yet. So, please add a JS-related sample or add support for this target build type.

Thank you.

**Comment by rodolphocouto** [comment]
Hey @night-crawler, Valiktor doesn't support JS because it's not multiplatform yet. We have plans to do that, but it is not so trivial because we have been using a lot of resources from Java standard library, mainly for i18n proposes.

Anyway, we can see value in multiplatform and it is in our roadmap. I'm closing this issue for now, let me know if you have any idea to help us with that. Thanks!

**Comment by rodolphocouto** [comment]
Referenced issue: #35.
